Create wigwag.js
photonle/Photon-Bot pull request #12
Opened 2019-12-22 16:21 UTC by GermanDude-ger

2019-12-22 16:31 UTC, JoshPiper requested changes

2019-12-22 16:31 UTC, JoshPiper commented on cmds/misc/wigwag.js
> +			}]
This can all be removed as it's not being used.

2019-12-22 16:31 UTC, JoshPiper commented on cmds/misc/wigwag.js
> +		}
Get rid of this switch, just have a single message.say returning.

2019-12-23 19:51 UTC, GermanDude-ger reviewed
Changed

2020-03-05 15:26 UTC, JoshPiper approved these changes

2020-03-05 15:27 UTC, merged